### PR TITLE
Color conversion to BGRA for recording files

### PR DESCRIPTION
**Pull request by RoseFlunder**
## Fixes #
#61 
Enables color conversion to BGRA for recording files.

### Description of the changes:
- If a recording file is opened and the color_enabled parameter is set, the conversion to BGRA will be set for the playback handle

### Before submitting a Pull Request:
- [x] I reviewed [CONTRIBUTING.md](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/CONTRIBUTING.md)
- [x] I [built my changes](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/docs/building.md) locally
- [ ] I tested my changes with a device
- [x] I tested my changes with a recording file

### I tested changes on: 
- [ ] Windows
- [x] Linux

manual testing

### CODE REVIEW

**Comment by skalldri** [comment]
@xthexder : do you know if there are any plans to support "transcoding" of recorded MKV files from one color format to another?

Before we go to far down the path of adding support in the ROS node, I'd like to get your input here.

**Comment by xthexder** [comment]
This is already supported with `k4a_playback_set_color_conversion(handle, K4A_IMAGE_FORMAT_COLOR_BGRA32)`

**Comment by RoseFlunder** [comment]
@xthexder 
Oh thats awesome. Thanks for the hint. I going to change this pullrequest then using the method from the SDK.

**Comment by RoseFlunder** [comment]
@skalldri
Pull request is edit and can be tested/reviewed.

**Review by skalldri — APPROVED** [review]
Looks good. Nice and simple change!

**Pull request merged**
