### PR TITLE
Use a separate thread to pop k4abt_tracker result. Fix #109.

### LINKED ISSUE #109: Body tracking latency
**Is your feature request related to a problem? Please describe.**
The body tracking data in the ROS driver is very useful to my application, but somehow there's about 1-second latency in the reported data. However, the data seen in the body tracking SDK is faster (about 0.25 second). 

**Describe the solution you'd like**
Is there any way to improve the body tracking data latency in the ROS driver to be close to the SDK's speed?

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by zchenpds**
### Description of the changes:
- Create a separate thread dedicated to popping the result from `k4abt_tracker_` and publishing body_tracking_data following the suggestion from [this post](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1130#issuecomment-598866234):
> the tracker will process faster if you keep queuing the frame without waiting for previous frame to be finished. Because then the pipeline can process two frames at different stages at the same time.

### Before submitting a Pull Request:
- [x] I reviewed [CONTRIBUTING.md](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/CONTRIBUTING.md)
- [x] I [built my changes](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/docs/building.md) locally
- [x] I tested my changes with a device
- [ ] I changed both the ROS1 and ROS2 branches

### I tested changes on: 
- [ ] Windows
- [x] Linux
- [x] ROS1
- [ ] ROS2

I measured the delay by adding `ROS_INFO_STREAM("Body tracking delay: " << (ros::Time::now() - capture_time).toSec() * 1000.0 << " ms.");` below Line 990 https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/87d10fad00a73c9bf13db530c63631e10e9fc96a/src/k4a_ros_device.cpp#L990 and run `roslaunch azure_kinect_ros_driver driver.launch fps:=30 depth_mode:=WFOV_2X2BINNED body_tracking_enabled:=true`. The delay increases quickly from 80 ms to around 280 ms on my laptop if/when I run some light-weight tasks such as opening a new webpage in Chrome browser or scrolling up/down in vscode editor. (Laptop specs: Intel® Core™ i7-9750H CPU @ 2.60GHz × 12 , GeForce RTX 2060, 32 GB RAM)

By moving https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/87d10fad00a73c9bf13db530c63631e10e9fc96a/src/k4a_ros_device.cpp#L990-L1039 to a separate thread, the delay was able to stay at around 80 ms regardless of what light-weight tasks I run.

Alternatively the delay can be measured by `printTimestampDebugMessage("Body tracking", capture_time);`, running `roslaunch azure_kinect_ros_driver driver.launch fps:=30 depth_mode:=WFOV_2X2BINNED body_tracking_enabled:=true imu_rate_target:=3` and change log verbosity level to debug.

### CODE REVIEW

**Comment by ooeygui** [comment]
Thank you for the contribution!

We need to keep the ROS1 and ROS2 trees in sync, can you make an equivalent fix to the Foxy branch and test on ROS2?

**Comment by zchenpds** [comment]
@ooeygui Sure. I will do it later today.

**Comment by ooeygui** [comment]
Sorry for the delay on this, we are working on validating it.

**Comment by zchenpds** [comment]
@amelhassan Please let me know if anything needs to fixed in this PR. I will lose access to the k4a device after this week so hopefully I can amend it to your satisfaction.

**Comment by amelhassan** [comment]
Yes I'll take a look today and let you know if any changes are needed.

**Review by amelhassan — APPROVED** [review]

**Pull request merged**
