### PR TITLE
Fixed node not shutting down, if sensor stream breaks

### LINKED ISSUE #181: Color stream breaks silently
**Describe the bug**
On some systems, the color stream breaks down.
This issue is reported in the SDK and the fix will
likely take some time (https://github.com/microsoft/Azure-Kinect-Sensor-SDK/issues/1354).

**To Reproduce**
1. Start the node on any computer using an 'unsupported' usb controler.
   Set 30 fps and color to 2160P
2. rostopic hz /rgb/image_raw
3. Wait some time, hz drops to zero

**Expected behavior**
The node shall crash if the color stream stalls.

The issue here is the 
`if (!k4a_device_.get_capture(&capture, std::chrono::milliseconds(K4A_WAIT_INFINITE)))`
(https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/melodic/src/k4a_ros_device.cpp#L825)
that waits forever in the case that the stream breaks.

I got a tested bugfix and can create a merge request as soon as this issue is approved.

### PR DESCRIPTION
**Pull request by jmachowinski**
Currently the node will break silently if the camera stops
sending data. This happens as it blocks infinite in
get_capture. This commit reduces the timeout to 5 times
the expected time it would normally take for a new frame
to arrive.
For unknown reasons, the first frame takes way longer to arrive,
therefore we wait up to four seconds for the first frame.

### Description of the changes:
-
-
-

### Required before submitting a Pull Request:
- [X] I reviewed [CONTRIBUTING.md](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/CONTRIBUTING.md)
- [X] I [built my changes](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/docs/building.md) locally
- [X] I tested my changes with a device
- [ ] I changed both the ROS1 and ROS2 branches

### I tested changes on: 
- [ ] Windows
- [X] Linux
- [X] ROS1
- [ ] ROS2

Test was performed on an AMD EPYC System with one camera, multiple stalls occurred,
node was shut down as expected. (And the restarted by roslaunch)

### CODE REVIEW

**Comment by RoseFlunder** [comment]
Just a small optimization idea computation wise:
You could initialize two variables instead of your bool:

```
auto waitTime = std::chrono::milliseconds(4 * 1000);
auto regularWaitTime = std::chrono::milliseconds(1000 * 5 / params_.fps);
```

Then after getting a capture you just assign waitTime to the shorter interval:
`waitTime = regularWaitTime`

So in the first iteration it takes the initial value and in all following iterations the smaller value.
Of you course you still have this one assignment every loop but its less than having to branch with a bool value and do the assigning inside the branches.

**Comment by ooeygui** [comment]
@jmachowinski Thank you for your contribution. We do need to keep both the ROS1 and ROS2 branches in sync, could you submit a pull request for the ROS2 build as well?

**Comment by jmachowinski** [comment]
@ooeygui I don't have an ros2 installation and currently also no time, to set it up.
I could cherry pick the commit on the foxy branch, and just open the pull request with
the request for someone to try it out though...

**Comment by jmachowinski** [comment]
@RoseFlunder 
I created a short version :
https://github.com/jmachowinski/Azure_Kinect_ROS_Driver/blob/timeout_fix2/src/k4a_ros_device.cpp
but is it still as readable and understandable as the initial patch ?

I normally prefer readability above minor performance optimizations...

**Comment by amelhassan** [comment]
Thank you for your contributions @jmachowinski , I made a ROS2 equivalent of your change, PR #205 . It would be great if you could update your PR with the same format for the changes. This takes into consideration @RoseFlunder suggestions but also keeps the readability in tact as you suggested.

**Comment by jmachowinski** [comment]
okay, I'll try to do this next week, thanks @amelhassan

**Comment by jmachowinski** [comment]
Updated, as requested, rebased on latest head.
Note, I also added two comments to make the code more obvious, and removed the TODO.

**Comment by amelhassan** [comment]
Looks good!

**Review by amelhassan — APPROVED** [review]

**Pull request merged**
