### PR TITLE
body_tracking_sample_tf_publisher

### PR DESCRIPTION
**Pull request by AswinkarthikeyenAK**
### Description of the changes:
- Added TF2 Broadcaster for body tracking

### Before submitting a Pull Request:
- [x] I reviewed [CONTRIBUTING.md](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/CONTRIBUTING.md)
- [x] I [built my changes](https://github.com/microsoft/Azure_Kinect_ROS_Driver/blob/master/docs/building.md) locally
- [x] I tested my changes with a device

### I tested changes on: 
- [ ] Windows
- [x] Linux

Manual Testing

### CODE REVIEW

**Comment by ooeygui** [comment]
Thank you for your contribution. Before we can pull it, please make the following changes:

* This repository is under an MIT license
* The extra message hop introduces latency, it would be better to add add joint state publishing to the existing marker publisher in C++?
* Could you make an equivalent change to the ROS2 branch?

Thank you
Lou

**Comment by AswinkarthikeyenAK** [comment]
Hi 
Sure I will make the changes and will update you
Thanks

**Comment by AswinkarthikeyenAK** [comment]
> Thank you for your contribution. Before we can pull it, please make the following changes:
> 
> * This repository is under an MIT license
> * The extra message hop introduces latency, it would be better to add add joint state publishing to the existing marker publisher in C++?
> * Could you make an equivalent change to the ROS2 branch?
> 
> Thank you
> Lou

Hi @ooeygui ,
I tried to modify the code to add the tf2 publlisher in order to publish tf frames. While doing so, I get the following error
`[ INFO] [1611363022.152502881]: rviz version 1.13.13
[ INFO] [1611363022.152561384]: compiled against Qt version 5.9.5
[ INFO] [1611363022.152580144]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1611363022.160021717]: Forcing OpenGl version 0.
[ INFO] [1611363022.679843865]: Stereo is NOT SUPPORTED
[ INFO] [1611363022.679917545]: OpenGl version: 4.6 (GLSL 4.6).
[ WARN] [1611363050.130722161]: OGRE EXCEPTION(7:InternalErrorException): Vertex Buffer: Out of memory in GLHardwareVertexBuffer::lock at /build/ogre-1.9-B6QkmW/ogre-1.9-1.9.0+dfsg1/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 124)
terminate called after throwing an instance of 'Ogre::InternalErrorException'
  what():  OGRE EXCEPTION(7:InternalErrorException): Vertex Buffer: Out of memory in GLHardwareVertexBuffer::lock at /build/ogre-1.9-B6QkmW/ogre-1.9-1.9.0+dfsg1/RenderSystems/GL/src/OgreGLHardwareVertexBuffer.cpp (line 124)` 

and RViz crashes. 

I am not sure what is causing this issue. can you kindly let me know if know how to fix this issue here?

Thanks

**Comment by ooeygui** [comment]
Closing this PR as it has been superseded

**Pull request closed without merging**
